---
title: "TidyTuesday 2024-38 Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

# Tidytuesday 2024-38

This is the notebook for analysis of the data of week 38 (2024) for the [tidytuesday](https://tidytues.day) project. The game is on!

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.width = 12, fig.height = 8, cache = TRUE)
library(tidyverse)
library(tidytuesdayR)
library(hrbrthemes)
library(scales)
library(lubridate)
library(ggrepel)
library(patchwork)
library(here)
library(gganimate)
library(patchwork)
library(camcorder)
library(ragg)
library(sysfonts)
library(figpatch)
library(patchwork)
library(magick)
library(grid)

sysfonts::font_add_google(name = "Cinzel", family = "cinzel")
showtext::showtext_auto()
# Set theme
theme_set(theme_ipsum() + theme(legend.position = "bottom"))

#Initialize Camcorder
gg_record(
  dir = file.path(getwd(), "camcorder"), 
  device = "png", 
  width = 15,     
  height = 18,   
  units = "in",  
  dpi = 300    
)

# Define default path for saving plots
plot_path <- here::here("output", paste0("tidytuesday_", 2024, "_", 38))
if (!dir.exists(plot_path)) {
  dir.create(plot_path, recursive = TRUE)
}

header_img <- system.file("../header.png")


```

Okay let us see what we have.

```{r}
# Load TidyTuesday Data
tuesdata <- tidytuesdayR::tt_load(2024, week = 38)

names(tuesdata)
glimpse(tuesdata[[1]])
hamlet <- tuesdata$hamlet
macbeth <- tuesdata$macbeth
romeo_juliet <- tuesdata$romeo_juliet
```



```{r}
library(tidytext)
library(ggbump)
library(ggtext)
library(glue)

create_bump_chart <- function(data, n = 4, play) {
  top_n <- data %>%
    filter(!character %in% c('[stage direction]', 'All')) %>%
    unnest_tokens(word, dialogue) %>%
    anti_join(stop_words) %>%
    count(character, sort = TRUE) %>%
    slice_head(n = n) %>%
    pull(character)
  
  act_levels <- c("Act I", "Act II", "Act III", "Act IV", "Act V")
  
  final_data <- data %>%
    filter(!character %in% c('[stage direction]', 'All')) %>%
    unnest_tokens(word, dialogue) %>%
    anti_join(stop_words) %>%
    count(act, character, name = "word_count") %>%
    group_by(character) %>%
    filter(n_distinct(act) >= 3) %>%
    group_by(act, character) %>%
    summarize(act_word_count = sum(word_count), .groups = "drop") %>%
    group_by(act) %>%
    mutate(
      act_rank = dense_rank(desc(act_word_count)),
      act = factor(act, levels = act_levels),
      is_top_n = character %in% top_n
    )
  
  final_order <- final_data %>%
    filter(act == act_levels[length(act_levels)]) %>%
    arrange(act_rank) %>%
    pull(character)
  
  shakespeare_colors <-
    c(c("#7f7f7f","#c27d38","#ccc591","#29211f","#5b2333"), rep("#7E7F9A", length(unique(
      final_data$character
    )) - n))
  names(shakespeare_colors) <-
    c(top_n, setdiff(unique(final_data$character), top_n))
  
  # Identify first and last appearances for each character
  char_appearances <- final_data %>%
    group_by(character) %>%
    summarize(
      first_act = min(as.numeric(act)),
      last_act = max(as.numeric(act)),
      .groups = "drop"
    )
  
  ggplot(final_data, aes(x = act, y = act_rank, group = character)) +
    
    geom_bump(aes(color = character, alpha = is_top_n), size = 2.5) +
    
    geom_point(aes(color = character, alpha = is_top_n), size = 4) +
   ggtext::geom_richtext(
      data = final_data %>% 
        inner_join(char_appearances, by = "character") %>%
        filter(as.numeric(act) == first_act),
      aes(
        x = ifelse(first_act == 1, as.numeric(act) - 0.1, as.numeric(act) - 0),
        label = ifelse(
          first_act == 1,
          glue("<span style='font-size:50pt;'><strong>{character}</strong><span style='color:#F6F4DF;'>...</span><span style='font-size:50pt; color: #23231A;'>**{act_rank}**</span></span>"),
          glue("<span style='font-size:30pt; color: #808080;'>{character}</span>")
        )
      ),
      color = "#23231A",
      hjust = ifelse(first_act == 1, 1, 1),
      label.color = NA,
      fill = NA
    ) +
    ggtext::geom_richtext(
      data = final_data %>% 
        inner_join(char_appearances, by = "character") %>%
        filter(as.numeric(act) == last_act),
      aes(
        x = ifelse(last_act == length(act_levels), as.numeric(act) + 0.1, as.numeric(act) + 0),
        label = ifelse(
          last_act == length(act_levels),
          glue("<span style='font-size:50pt;'><span style='font-size:50pt; color: #23231A;'>**{act_rank}**</span><span style='color:#F6F4DF; background:{character}'>...</span><strong>{character}</strong></span>"),
          glue("<span style='font-size:30pt; color: #808080;'>{character}</span>")
        )
      ),
      color = "#23231A",
      hjust = ifelse(last_act == length(act_levels), 0, 0),
      label.color = NA,
      fill = NA
    ) +
    scale_y_reverse(
      breaks = 1:max(final_data$act_rank),
      labels = 1:max(final_data$act_rank)
    ) +
    scale_alpha_manual(values = c(0.1, 1), guide = "none") +
    scale_color_manual(values = shakespeare_colors, breaks = final_order) +
    scale_x_discrete(limits = c(act_levels), position = "top") +
    cowplot::theme_minimal_grid() +
    labs(
      title = paste(play),
      x = "Act",
      y = "Rank",
      color = "Character"
    ) +
    coord_cartesian(clip = "off") +
    theme(
      legend.position = "none",
      panel.grid.major.y = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      axis.text.y = element_blank(),
      axis.text.x = element_text(size = 46, margin = margin(0, 0, 100, 0)),
      plot.title = element_text(
        face = "bold",
        size = 80,
        family = "cinzel",
        colour = "#23231A",
        hjust = 0.5,
        margin = margin(20, 0, 20, 0, unit = "pt")
      ),
      plot.subtitle = element_text(size = 12, color = "darkgrey"),
      axis.title = element_text(face = "bold"),
      legend.title = element_text(face = "bold"),
      plot.margin = margin(20, 150, 20,150, unit = "pt")
    )
}
h <- create_bump_chart(hamlet, n = 5, "Hamlet")
m <- create_bump_chart(macbeth, n = 5, "Macbeth")
r <- create_bump_chart(romeo_juliet, n = 5, "Romeo and Juliet")




header_img <- image_read("header.png")

header_raster <- as.raster(header_img)

header_plot <- ggplot() +
  annotation_custom(rasterGrob(header_raster, interpolate = TRUE), xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  theme_void()

text_plot <- ggplot() +
  theme_void() +
  annotate("text", x = 0.5, y = 0.9, 
           label = str_wrap("Tracking Shakespeare's Key Players", width = 55),
           hjust = 0.5, vjust = 1.5, size = 40, fontface = "bold", family = "cinzel", lineheight = 0.3) +
  annotate("text", x = 0.5, y = 0.1, 
           label = str_wrap("How character prominence shifts across five acts in Hamlet, Macbeth, and Romeo and Juliet based on dialogue frequency", width = 65),
           hjust = 0.5, vjust = -0.8, size = 20, lineheight = 0.4) +
  theme(
    plot.background = element_rect(fill = "#F6F4DF", color = NA)
  )

# Combine all plots
combined_plot <- header_plot +
  text_plot +
  (h + m + r + plot_layout(nrow = 3, ncol = 1)) +
  plot_layout(nrow = 3, heights = c(0.2, 0.2, 1)) +
  plot_annotation(
    caption = "Tidytuesday Week 38 | Graphic by Aman Bhargava",
    theme = theme(
      plot.background = element_rect(fill = "#F6F4DF"),
      plot.margin = margin(20, 20, 40, 20),
      plot.caption = element_text(size = 32, hjust = 0.5, margin = margin(20, 0, 0, 0))
    )
  )

combined_plot

ggsave(
  filename = "combined_plot.png",
  plot = combined_plot,
  width = 16,
  height = 20,
  units = "in",
  dpi = 300
)
  img <- image_read("./combined_plot.png")

img_with_noise <- img %>%
  image_noise("gaussian") %>%
  mage_noise("gaussian") %>%
  image_modulate(brightness = 100, saturation = 95) %>%
  image_contrast(sharpen = 1)

 img_with_noise

  
```



